version: '3'

services:
  node:
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
    user: "1000:1000"
    container_name: chameleos-node
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    restart: unless-stopped
    ports:
      - "80:8080"
