version: '3'

services:
  node:
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
    container_name: chameleos-node
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    restart: unless-stopped
    ports:
      - "80:8080"
volumes:
  node_modules:
