version: '3'

services:
  node:
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
    container_name: chameleos-node
    volumes:
      - node_modules:/var/www/node_modules
      - .:/var/www
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "80:8080"
volumes:
  node_modules:
